import { AuthProvider } from "@/contexts/AuthContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "La Granja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="w-full px-8 h-screen overflow-y-scroll">
            {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
