import SideBar from './componeents/sideBar'
import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex">
        <SideBar />
        <div className='w-full max-h-screen overflow-y-auto'>
          {children}
        </div>
      </body>
    </html>
  )
}
