import SideBar from './componeents/sideBar'
import './globals.css'

export const metadata = {
  title: 'La Granja',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex">
        <SideBar />
        <div className='w-full max-h-screen overflow-y-scroll'>
          {children}
        </div>
      </body>
    </html>
  )
}
